# Generated by Django 2.0.1 on 2018-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AddField(
            model_name='news',
            name='autor',
            field=models.ManyToManyField(to='news.Autor', verbose_name='Autor'),
        ),
    ]
