# Generated by Django 2.0.1 on 2018-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180128_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ikona',
            field=models.CharField(max_length=100, verbose_name='Ikonka Kategorii'),
        ),
    ]
