# Generated by Django 2.0.1 on 2018-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180129_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='autor',
            field=models.ManyToManyField(to='news.Autor', verbose_name='Autor'),
        ),
    ]
