# Generated by Django 2.0.1 on 2018-01-29 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180129_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='autor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
