# Generated by Django 2.0.1 on 2018-01-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180130_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
