# Generated by Django 2.0.1 on 2018-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180202_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ikona',
            field=models.ImageField(blank=True, upload_to='icons', verbose_name='Ikonka Kategorii'),
        ),
    ]
